server:
  port: 8080
  servlet:
    encoding: # 设置http编码为utf-8
      charset: UTF-8
      force: true
    session:
      timeout:
spring:
  application:
    name: management
  jackson:
    # null值不参与序列化
    default-property-inclusion: NON_NULL
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    druid:
      # druid监控页面
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      web-stat-filter:
        enabled: true
        # 排除不必要拦截的url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        url-pattern: /*
        # 关闭session统计功能
        session-stat-enable: false
      filter:
        wall:
          enabled: true
        stat:
          enabled: true
          # 慢sql记录
          log-slow-sql: true
          # sql合并
          merge-sql: true
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml

logging:
  level:
    cn.tucci: debug